# Site settings
title: Toolkit for YNAB | Unofficial Browser Extension for You Need a Budget
email: kevinbrowntech@gmail.com
description: >
  A free, open source browser extension for You Need a Budget, adding
  tweaks and additional features for a more customizable experience.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://toolkitforynab.com" # the base hostname & protocol for your site
twitter_username: kevinbrowntech
github_username:  blargity

# GitHub Pages Redirects
plugins:
  - jekyll-redirect-from
  - jekyll-postcss
  - jekyll-purgecss

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - README.md
  - tailwind.config.js
  - postcss.config.js
  - purgecss.config.js
  - .gitignore
